version: '3'
tasks:
  winres:
    platforms:
      - windows
    desc: Generate windows build resource
    # go install github.com/tc-hib/go-winres@latest
    cmd: go-winres make --arch amd64,arm64
  build:
    desc: Build executable files
    env:
      CGO_ENABLED: 0
    vars:
      GIT_COMMIT:
        sh: git rev-parse --short HEAD
      GIT_TAG:
        sh: git describe --tags --abbrev=0
    cmds:
      - go build -ldflags="-s -w -X main.build={{.GIT_COMMIT}} -X main.version={{.GIT_TAG}} -H=windowsgui" -trimpath -o out/gohomo.exe .