version: '3'
tasks:
  install-winres:
    internal: true
    desc: Check and install go-winres
    # 如果 go-winres help 执行失败，说明没安装或不在 PATH 中，则触发安装
    status:
      - go-winres help
    cmds:
      - echo "No go-winres found, trying to install..."
      - go install github.com/tc-hib/go-winres@latest
  winres:
    platforms:
      - windows
    desc: Generate windows build resource
    deps:
      - install-winres
    cmd: go-winres make --arch amd64,arm64
  build:
    desc: Build executable files
    env:
      CGO_ENABLED: 0
    vars:
      GIT_COMMIT:
        sh: git rev-parse --short HEAD
      GIT_TAG:
        sh: git describe --tags --abbrev=0
    cmds:
      - go mod tidy
      - go build -ldflags="-s -w -X main.build={{.GIT_COMMIT}} -X main.version={{.GIT_TAG}} -H=windowsgui" -trimpath -o out/gohomo.exe .